
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 28 14:48:23 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 17;
  public static final int CONST = 15;
  public static final int PERIOD = 31;
  public static final int NOT_EQUAL = 35;
  public static final int GREATER = 36;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int LESS = 38;
  public static final int MINUS = 12;
  public static final int RPAREN = 7;
  public static final int AND = 27;
  public static final int OR = 26;
  public static final int COMMA = 8;
  public static final int CLASS = 19;
  public static final int INC = 29;
  public static final int DIV = 33;
  public static final int LESS_EQUAL = 39;
  public static final int PLUS = 11;
  public static final int IF = 40;
  public static final int ASSIGN = 16;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 18;
  public static final int EQUAL = 13;
  public static final int GREATER_EQUAL = 37;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int NUMBER = 42;
  public static final int MOD = 34;
  public static final int IDENT = 43;
  public static final int BREAK = 23;
  public static final int VOID = 14;
  public static final int ELSE = 41;
  public static final int LBRACE = 3;
  public static final int READ = 25;
  public static final int WHILE = 22;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 20;
  public static final int PROG = 2;
  public static final int STRING = 44;
  public static final int DEC = 30;
  public static final int PRINT = 9;
  public static final int DO = 21;
}

