
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
	/* terminals */

	//KLJUCNE RECI
	public static final int PROG = 1;
	public static final int PRINT = 2;
	public static final int RETURN = 3;
	public static final int VOID = 4;
	public static final int IF = 5;
	public static final int ELSE = 6;
	public static final int BREAK = 7;
	public static final int CLASS = 8;
	public static final int NEW = 9; 
	public static final int READ = 10;
	public static final int DO = 11;
	public static final int WHILE = 12;
	public static final int EXTENDS = 13;
	public static final int CONTINUE = 14;
	
	//OPERATORI
	public static final int PLUS = 15;
	public static final int MINUS = 16;
	public static final int MUL = 17;
	public static final int DIV = 18;
	public static final int MOD = 19;
	public static final int EQUAL = 20;
	public static final int NOT_EQUAL = 21;
	public static final int GREATER = 22;
	public static final int GREATER_EQUAL = 23;
	public static final int LESS = 24;
	public static final int LESS_EQUAL = 25;
	public static final int AND = 26;
	public static final int OR = 27;
	public static final int ASSIGN = 28;
	public static final int INC = 29;
	public static final int DEC = 30;
	public static final int SEMI = 31;
	public static final int COMMA = 32;
	public static final int PERIOD = 33;
	public static final int LPAREN = 34;
	public static final int RPAREN = 35;
	public static final int LBRACKET = 36;
	public static final int RBRACKET = 37;
	public static final int LBRACE = 38;
	public static final int RBRACE = 39;

	//VRSTE TOKENA
	public static final int IDENT = 40;
	public static final int NUMBER = 42;
	public static final int STRING = 43;
	public static final int BOOLEAN = 44;
	
	public static final int error = 1;
	public static final int EOF = 41;
  
	  
}

